### ISSUE TITLE
Error during API call when using run-bypass.py

### ISSUE THREAD

**Issue by Avidity-la** [adhe222/nodepaybot#1]
![20241130220651](https://github.com/user-attachments/assets/8d43f512-c4bd-44e2-aff1-6cce2b043f29)
When running  run-bypass.py, API Call Read Timeout and ping failed with proxy
when running run.py, proxy was forbiddened by cf , getting errors like ```Error during API call: 403 Client Error: Forbidden for url```

**Comment by adhe222** [comment]
git pull
pip install -r requirements.txt

done..
