### ISSUE TITLE
Ping failed sir

### ISSUE THREAD

**Issue by iamaruf05** [adhe222/nodepaybot#3]
i am getting this issue URL https://nw.nodepay.org/api/network/ping and proxy http://sps3sqfx6k:u5mcN=mnF9Is6k3jyR@isp.smartproxy.com:10013: Failed API call to https://nw.nodepay.org/api/network/ping

and run-bypass.py is not in the file. can you help me?

**Comment by adhe222** [comment]
git pull

just installl
pip install -r requirements.txt
put your proxies at local_proxies.txt, put ur token at token_list.txt and then python run-multi-bypass.py

**Comment by iamaruf05** [comment]
<img width="348" alt="image" src="https://github.com/user-attachments/assets/96aaf7d2-844a-47cb-a499-99c4f3d705ad">
getting this sir. i followed every step you provided
